# Generated by Django 6.1.1 on 2026-10-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='originals/%Y/%m/')),
                ('medium', models.FileField(blank=True, upload_to='medium/%Y/%m/')),
                ('thumb', models.FileField(blank=True, upload_to='thumbs/%Y/%m/')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created', 'id'],
            },
        ),
    ]
